# Automatically generated by: ros2nix --flake --distro humble
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "humble",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths =
        [
          pkgs.colcon
          pkgs.rosPackages.${rosDistro}.ros-core

          # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
          pkgs.rosPackages.${rosDistro}.ament-cmake-core
          pkgs.rosPackages.${rosDistro}.python-cmake-module
        ]
        ++ (
          with pkgs;
          with pkgs.rosPackages.${rosDistro};
          with extraPkgs;
          [
            # Dependencies from package.xml files
            action-msgs
            ament-cmake
            ament-cmake-mypy
            ament-cmake-pytest
            ament-cmake-python
            ament-cmake-ros
            builtin-interfaces
            control-msgs
            diagnostic-msgs
            example-interfaces
            geometry-msgs
            launch
            launch-ros
            launch-testing-ament-cmake
            nav-msgs
            python3Packages.autobahn
            python3Packages.cbor2
            python3Packages.numpy
            python3Packages.pillow
            python3Packages.tornado
            python3Packages.twisted
            python3Packages.ujson
            rcl-interfaces
            rclpy
            rmw-dds-common
            ros2action
            ros2interface
            ros2node
            ros2service
            ros2topic
            rosidl-adapter
            rosidl-default-generators
            rosidl-default-runtime
            #rosidl-pycommon
            rosidl-runtime-py
            sensor-msgs
            shape-msgs
            std-msgs
            std-srvs
            stereo-msgs
            tf2-msgs
            trajectory-msgs
            visualization-msgs
          ]
        )
        ++ builtins.attrValues extraPkgs
        ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
      }
    )
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
